# Generated by Django 4.2.20 on 2025-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="dose",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="medicine",
            name="dose_measurement",
            field=models.CharField(
                choices=[
                    ("mg", "mg"),
                    ("g", "g"),
                    ("mcg", "mcg"),
                    ("mL", "mL"),
                    ("L", "L"),
                    ("IU", "IU"),
                    ("U", "U"),
                    ("tsp", "tsp"),
                    ("tbsp", "tbsp"),
                    ("gtt", "gtt"),
                    ("puff", "puff"),
                ],
                default="mg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="brand",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
