# Generated by Django 4.2.20 on 2025-03-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0003_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="medicine.supplier",
            ),
            preserve_default=False,
        ),
    ]
