# Generated by Django 4.2.20 on 2025-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0004_medicine_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(default="lachlan@gmail.com", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="username",
            field=models.CharField(default="lachlan", max_length=256),
            preserve_default=False,
        ),
    ]
