# Generated by Django 4.2.20 on 2025-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0006_alter_supplier_email_alter_supplier_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="username",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
