# Generated by Django 4.2.20 on 2025-04-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0010_alter_invoice_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
