# Generated by Django 4.2.20 on 2025-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0011_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
