# Generated by Django 4.2.20 on 2025-04-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0012_invoice_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="gst",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
